### PR TITLE
fix test names not incorporating describe blocks

### LINKED ISSUE #4: `describe` block name ignored when building test name
The test name does not contain the `describe` block name. Thus it fails to build unique test names, even they are defined uniquely.

### PR DESCRIPTION
**Pull request by sebastianhaeni**

### CODE REVIEW

File: src/Reporters/ConsoleReporter.ts [hunk 1]
```diff
@@ -30,10 +30,13 @@ export default class ConsoleReporter {
...
     const titlePath = test.titlePath();
+    const titlePathWithoutExtra = titlePath.filter(
+      (title) => title !== 'extra' && title !== 'Extra',
+    );
 
     this.getTestRun().recordTest(
-      titlePath.filter((title) => title !== 'extra' && title !== 'Extra').join(' > '),
-      test.title,
+      titlePathWithoutExtra.join(' > '),
+      titlePathWithoutExtra.slice(1).join(' > '),
```
Comment (sebastianhaeni) [inline src/Reporters/ConsoleReporter.ts:39]: I'm not super happy about this solution. If you have a better idea, please let me know or take over :)

Comment (cyrilwanner) [reply src/Reporters/ConsoleReporter.ts:39]: I am actually not sure if we should solve the problem like this. I see now why it occurred, I initially was thinking that the tests displayed in the list should be as short as possible because when you add all nested describes, it's just repeated all the time and harder to read.

So instead of having one big group with all the tests, I would recommend having separate smaller groups. That's maybe also easier for competitors to see their points or in which part they still have many tests missing.

Example with one big group:
image


Same split into smaller groups:
image


Nevertheless, I will merge this as it is since it will solve the error we are facing and I don't have too much time to think about a different way today.

For the future, we may want to think about how we map nested test names to groups, maybe there is a better solution in general.

**Review by cyrilwanner — APPROVED** [review]
